### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [rogeliosamuel621/rs-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by sam-621** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.
> 
> Thanks!

Oh, great :D, I'll add it

**Comment by sam-621** [comment]
There is already a screenshot in the project

**Comment by unixorn** [comment]
Weird, I didn't see it when I made the issue, sorry about that.
